default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_general_ci
  pool: <%= ENV.fetch("WJ_API_MAX_THREAD") { 5 } %>

development:
  <<: *default
  database: torutoru
  username: root
  password:
  socket: /Applications/XAMPP/xamppfiles/var/mysql/mysql.sock

